tests: Remove bogus type parameter for Protocol
The tests are not currently type checked (files = "src") and have many
mypy errors yet to be addressed.  But this didn’t even work at
_runtime_, because CommandTester is a class, not a type variable.

$ poetry run python -m tests.types
Traceback (most recent call last):
  File "…/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "…/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anders/python/poetry-plugin-export/tests/types.py", line 18, in <module>
    class CommandTesterFactory(Protocol[CommandTester]):
  File "…/lib/python3.9/typing.py", line 277, in inner
    return func(*args, **kwds)
  File "…/lib/python3.9/typing.py", line 997, in __class_getitem__
    raise TypeError(
TypeError: Parameters to Protocol[...] must all be type variables

Signed-off-by: Anders Kaseorg <andersk@mit.edu>